### ISSUE TITLE
[imdbParser.py] Runtime error?

### ISSUE THREAD

**Issue by MrHohn** [MrHohn/MovieRecommend#1]
- When I did:
  python imdbParser.py
- I got:
  [mongo] Initializing database: [imdb]
  === Starting Parse of movies.list ===
  Traceback (most recent call last):
  File "imdbParser.py", line 23, in <module>
    imdbMovies.parse(mongo, collectionName)
  File "C:\Users\Think\Documents\GitHub\MovieRecommend\imdbMovies.py", line 27, in parse
    with open("imdbdata/movies.list", encoding="latin1") as tsv:
  TypeError: 'encoding' is an invalid keyword argument for this function
  [mongo] Closing all connections

I already put the necessary lists into imdbdata folder. Would it be something wrong with my python library?

**Comment by AndrewFM** [comment]
It's probably your python version, I'm using 3.4. Older versions of python have an older version of the csv library that doesn't support utf-8 or other file encodings (only supports ascii files).

**Comment by MrHohn** [comment]
You are right. I switch from 2.7 to 3.4 and it works great, thx!
