### ISSUE TITLE
About retrieving full imdb titles.

### ISSUE THREAD

**Issue by MrHohn** [MrHohn/MovieRecommend#3]
I tried a few approaches to retrieve the full imdb title for all movies but encounterred many issues and none of my approaches guarantee I would gain correct imdb titles for all movies, hence raised errors while combining with the UI.

I still think returning imdb ids is a good way to handle this, Since in the UI, we are also using OMDB api for retrieving the infomation of movies instead of our local database. Hence it doesn't matter whether we have the imdb ids locally or not. And the unique imdb id would guarantee we got the right one.

**Comment by MrHohn** [comment]
I made a mistake...

Since we are now combining the IMDB and MovieLens datasets, we would need either the full imdb title or the imdb id locally to do the union. Under this consideration, retrieving the full imdb title is actually the better way.

Currently the issues I have is OMDB API only provide partial imdb title, and it is hard to convert it into a full one. Querying the partial imdb title in our local imdb database also raise errors because movie name duplications.

Any other good ways for getting imdb titles for the movies in MovieLens dataset?

**Comment by AndrewFM** [comment]
Instead of querying on just the title alone, can you avoid duplicates by querying on title+year, or title+year+country?

**Comment by MrHohn** [comment]
That would work, I came up with it and added it in commit f020319550dd31477c9f71706c7ea351289633bb.

Also I temporarily filter out the movies without a valid imdb title (about 700 movies) to at least make the system runnable.

Thanks for pointing out!

**Comment by MrHohn** [comment]
Closing staled issue.
